window.LITERATURE_DATA = {
  meta: {
    version: "0.1.0",
    lastUpdated: "2026-04-16",
  },
  modelLabels: {
    qpm: { en: "QPM", ru: "КПМ", uz: "CPM" },
    dfm: { en: "DFM", ru: "ДФМ", uz: "DFM" },
    cge: { en: "CGE", ru: "CGE", uz: "CGE" },
    io: { en: "Input-Output", ru: "Межотраслевой баланс", uz: "Tarmoqlararo balans" },
    pe: { en: "Partial Equilibrium", ru: "Частичное равновесие", uz: "Qisman muvozanat" },
    fpp: { en: "FPP", ru: "ФПП", uz: "MDS" },
  },
  papers: [
    {
      id: "berg-2006-qpm",
      model: "qpm",
      topic: "monetary",
      title: "Quarterly Projection Model for Small Open Economies",
      authors: "Berg, Karam, Laxton",
      year: 2006,
      venue: "IMF Working Paper",
      doi: "10.5089/9781451863322.001",
      url: "https://www.imf.org/",
      abstract: "Framework for inflation-targeting policy analysis in small open economies using a tractable quarterly model.",
      relevance: {
        en: "Foundational design template for policy-rate transmission and inflation targeting in the Uzbekistan QPM setup.",
        ru: "Базовый шаблон построения передачи ставки и инфляционного таргетирования для КПМ Узбекистана.",
        uz: "O'zbekiston CPMida stavka uzatmasi va inflyatsion targetlash uchun asosiy dizayn andozasi.",
      },
    },
    {
      id: "laxton-2009-fp",
      model: "qpm",
      topic: "monetary",
      title: "Forecasting and Policy Analysis System",
      authors: "Laxton, Rose, Scott",
      year: 2009,
      venue: "IMF Technical Note",
      doi: "",
      url: "https://www.imf.org/",
      abstract: "Operational architecture linking core model, forecast rounds, and policy communication.",
      relevance: {
        en: "Useful for institutionalizing the forecast-policy workflow around the QPM.",
        ru: "Полезно для институционализации цикла прогноз-политика вокруг КПМ.",
        uz: "CPM atrofida prognoz-siyosat ish jarayonini institutsionalizatsiya qilishda foydali.",
      },
    },
    {
      id: "banbura-2014-dfm",
      model: "dfm",
      topic: "nowcasting",
      title: "Maximum Likelihood Estimation of Dynamic Factor Models on Datasets with Arbitrary Pattern of Missing Data",
      authors: "Banbura, Modugno",
      year: 2014,
      venue: "Journal of Applied Econometrics",
      doi: "10.1002/jae.2306",
      url: "https://onlinelibrary.wiley.com/",
      abstract: "ML estimation approach for large mixed-frequency datasets with ragged edges.",
      relevance: {
        en: "Directly supports missing-pattern handling in real-time GDP nowcasting pipelines.",
        ru: "Напрямую поддерживает обработку пропусков в реальном времени для nowcast ВВП.",
        uz: "YaIM nowcast tizimida real vaqt rejimida yetishmayotgan ma'lumotlarni qayta ishlashga bevosita mos.",
      },
    },
    {
      id: "giannone-2008-nowcasting",
      model: "dfm",
      topic: "nowcasting",
      title: "Nowcasting: The Real-Time Informational Content of Macroeconomic Data",
      authors: "Giannone, Reichlin, Small",
      year: 2008,
      venue: "Journal of Monetary Economics",
      doi: "10.1016/j.jmoneco.2008.05.010",
      url: "https://www.sciencedirect.com/",
      abstract: "Classical nowcasting framework combining staggered releases into current-quarter GDP estimates.",
      relevance: {
        en: "Canonical reference for release-calendar aware nowcasting logic.",
        ru: "Каноническая работа по логике nowcast с учетом календаря публикаций.",
        uz: "Nashr taqvimi hisobga olingan nowcast mantiqi uchun klassik manba.",
      },
    },
    {
      id: "devarajan-1990-cge",
      model: "cge",
      topic: "trade",
      title: "Simple General Equilibrium Modeling",
      authors: "Devarajan, Lewis, Robinson",
      year: 1990,
      venue: "World Development",
      doi: "10.1016/0305-750X(90)90006-2",
      url: "https://www.sciencedirect.com/",
      abstract: "Compact CGE structure suitable for policy counterfactuals in developing economies.",
      relevance: {
        en: "Methodological backbone for the 1-2-3 style CGE module in the platform.",
        ru: "Методологическая основа модуля CGE типа 1-2-3 на платформе.",
        uz: "Platformadagi 1-2-3 uslubidagi CGE moduli uchun metodologik asos.",
      },
    },
    {
      id: "devarajan-1997-123",
      model: "cge",
      topic: "trade",
      title: "The 1-2-3 Model and Applied Trade Policy Analysis",
      authors: "Devarajan et al.",
      year: 1997,
      venue: "World Bank Working Note",
      doi: "",
      url: "https://www.worldbank.org/",
      abstract: "Practical closure rules and calibration guidance for trade and fiscal experiments.",
      relevance: {
        en: "Provides closure and calibration conventions used in Uzbekistan trade-policy simulations.",
        ru: "Дает правила замыкания и калибровки для торгово-фискальных симуляций Узбекистана.",
        uz: "O'zbekiston savdo-fiskal simulyatsiyalarida ishlatiladigan yopilish va kalibrlash qoidalarini beradi.",
      },
    },
    {
      id: "leontief-1986-io",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Economics",
      authors: "Wassily Leontief",
      year: 1986,
      venue: "Oxford University Press",
      doi: "",
      url: "https://global.oup.com/",
      abstract: "Foundational treatment of inter-industry linkage analysis and multiplier mechanics.",
      relevance: {
        en: "Primary conceptual source for output and value-added multiplier interpretation.",
        ru: "Базовый источник для интерпретации мультипликаторов выпуска и добавленной стоимости.",
        uz: "Ishlab chiqarish va qo'shilgan qiymat multiplikatorlarini talqin qilishning asosiy manbasi.",
      },
    },
    {
      id: "miller-blair-2009",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Analysis: Foundations and Extensions",
      authors: "Miller, Blair",
      year: 2009,
      venue: "Cambridge University Press",
      doi: "",
      url: "https://www.cambridge.org/",
      abstract: "Modern reference on I-O coefficients, multipliers, and regional extensions.",
      relevance: {
        en: "Supports sector-level multiplier diagnostics and scenario communication.",
        ru: "Поддерживает диагностику мультипликаторов по секторам и коммуникацию сценариев.",
        uz: "Tarmoqlar kesimida multiplikator diagnostikasi va ssenariy kommunikatsiyasini qo'llab-quvvatlaydi.",
      },
    },
    {
      id: "wits-smart-guide",
      model: "pe",
      topic: "trade",
      title: "WITS-SMART User Guide",
      authors: "World Bank",
      year: 2020,
      venue: "Technical Manual",
      doi: "",
      url: "https://wits.worldbank.org/",
      abstract: "Documentation of SMART formulas for trade creation, diversion, and tariff revenue.",
      relevance: {
        en: "Direct specification source for PE tariff scenario calculations.",
        ru: "Прямой источник спецификации расчетов тарифных сценариев в модели ЧР.",
        uz: "QM tarif ssenariylari hisob-kitoblari uchun bevosita spetsifikatsiya manbasi.",
      },
    },
    {
      id: "laird-yeats-trade",
      model: "pe",
      topic: "trade",
      title: "Quantitative Methods for Trade-Policy Analysis",
      authors: "Laird, Yeats",
      year: 1990,
      venue: "Macmillan",
      doi: "",
      url: "https://www.worldcat.org/",
      abstract: "Classical partial-equilibrium methods for tariff and welfare incidence analysis.",
      relevance: {
        en: "Provides assumptions and interpretation standards for PE welfare metrics.",
        ru: "Задает предпосылки и стандарты интерпретации показателей благосостояния в ЧР.",
        uz: "QM farovonlik ko'rsatkichlarini talqin qilish uchun farazlar va standartlarni beradi.",
      },
    },
    {
      id: "imf-fp-manual",
      model: "fpp",
      topic: "fiscal",
      title: "Financial Programming and Policies",
      authors: "IMF Institute",
      year: 2013,
      venue: "Training Manual",
      doi: "",
      url: "https://www.imf.org/",
      abstract: "Integrated macro-consistency framework linking real, fiscal, external, and monetary blocks.",
      relevance: {
        en: "Core reference for consistency checks and accounting identities in the FPP module.",
        ru: "Ключевой источник по проверкам согласованности и тождествам в модуле ФПП.",
        uz: "MDS modulida moslik tekshiruvlari va hisob identifikatsiyalari uchun asosiy manba.",
      },
    },
    {
      id: "mussa-savastano-1999",
      model: "fpp",
      topic: "fiscal",
      title: "The IMF Approach to Economic Stabilization",
      authors: "Mussa, Savastano",
      year: 1999,
      venue: "NBER Macroeconomics Annual",
      doi: "10.1086/654424",
      url: "https://www.nber.org/",
      abstract: "Discussion of stabilization design, program consistency, and policy trade-offs.",
      relevance: {
        en: "Useful framing for translating simulation outputs into policy narratives.",
        ru: "Полезная рамка для перевода симуляционных результатов в политические выводы.",
        uz: "Simulyatsiya natijalarini siyosiy xulosalarga aylantirish uchun foydali yondashuv.",
      },
    },
    {
      id: "openalex-nowcasting-survey",
      model: "dfm",
      topic: "nowcasting",
      title: "Real-Time GDP Nowcasting: A Survey",
      authors: "Various",
      year: 2022,
      venue: "OpenAlex Indexed Survey",
      doi: "",
      url: "https://openalex.org/",
      abstract: "Survey of machine-learning and factor approaches for quarterly GDP nowcasting.",
      relevance: {
        en: "Benchmark reference for extending DFM with robust real-time diagnostics.",
        ru: "Ориентир для расширения DFM устойчивой диагностикой в реальном времени.",
        uz: "DFMni real vaqt diagnostikasi bilan kengaytirish uchun etalon manba.",
      },
    },
    {
      id: "imf-qpm-low-income",
      model: "qpm",
      topic: "monetary",
      title: "Developing a QPM for Low-Income Economies",
      authors: "IMF Staff",
      year: 2017,
      venue: "IMF Working Paper",
      doi: "",
      url: "https://www.imf.org/",
      abstract: "Adaptation of forecasting and policy analysis systems to data-limited environments.",
      relevance: {
        en: "Highly relevant for small open economies with evolving data systems.",
        ru: "Высокая релевантность для малых открытых экономик с развивающейся статистикой.",
        uz: "Ma'lumot tizimi rivojlanayotgan kichik ochiq iqtisodiyotlar uchun juda dolzarb.",
      },
    },
    {
      id: "armington-1969",
      model: "cge",
      topic: "trade",
      title: "A Theory of Demand for Products Distinguished by Place of Production",
      authors: "Armington",
      year: 1969,
      venue: "IMF Staff Papers",
      doi: "10.2307/3866403",
      url: "https://www.imf.org/",
      abstract: "Foundational import-demand assumption used in most applied CGE models.",
      relevance: {
        en: "Key theoretical basis for the import-substitution block in the CGE module.",
        ru: "Ключевая теория для блока импортозамещения в модуле CGE.",
        uz: "CGE modulidagi import o'rnini bosish bloki uchun asosiy nazariy manba.",
      },
    },
    {
      id: "cet-trade-supply",
      model: "cge",
      topic: "trade",
      title: "Export-Domestic Transformation Functions in Applied CGE",
      authors: "Various",
      year: 2011,
      venue: "Applied Economics Note",
      doi: "",
      url: "https://ideas.repec.org/",
      abstract: "Comparative evidence on CET elasticity assumptions and export response.",
      relevance: {
        en: "Supports calibration of export transformation elasticity in the 1-2-3 framework.",
        ru: "Поддерживает калибровку эластичности трансформации экспорта в модели 1-2-3.",
        uz: "1-2-3 modelida eksport transformatsiya elastikligini kalibrlashni qo'llab-quvvatlaydi.",
      },
    },
    {
      id: "regional-io-chains",
      model: "io",
      topic: "multipliers",
      title: "Regional Input-Output Linkages and Industrial Policy",
      authors: "Various",
      year: 2018,
      venue: "Policy Studies",
      doi: "",
      url: "https://www.oecd.org/",
      abstract: "Evidence on regional spillovers and multiplier concentration across sectors.",
      relevance: {
        en: "Helpful for communicating oblast-level effects from sectoral demand shocks.",
        ru: "Полезно для объяснения региональных эффектов отраслевых шоков спроса.",
        uz: "Tarmoq talab shoklarining viloyat darajasidagi ta'sirini tushuntirishda foydali.",
      },
    },
    {
      id: "caem-country-applications",
      model: "fpp",
      topic: "fiscal",
      title: "Country Applications of IMF's CAEM Framework",
      authors: "IMF Teams",
      year: 2021,
      venue: "IMF Technical Papers",
      doi: "",
      url: "https://www.imf.org/",
      abstract: "Case-based applications of integrated macro-consistency projections.",
      relevance: {
        en: "Provides practical templates for aligning projections and policy constraints in FPP.",
        ru: "Дает практические шаблоны согласования прогнозов и ограничений политики в ФПП.",
        uz: "MDSda prognozlar va siyosat cheklovlarini moslashtirish uchun amaliy andozalar beradi.",
      },
    },
  ],
};
