import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import i18next from 'i18next'
import { initReactI18next, I18nextProvider } from 'react-i18next'
import { MemoryRouter } from 'react-router-dom'
import { renderToStaticMarkup } from 'react-dom/server'
import { InterpretationPanel } from '../../../src/components/scenario-lab/InterpretationPanel.js'
import type { ScenarioLabInterpretation } from '../../../src/contracts/data-contract.js'

async function createTestI18n(lng = 'en') {
  const instance = i18next.createInstance()
  await instance.use(initReactI18next).init({
    lng,
    fallbackLng: 'en',
    defaultNS: 'common',
    ns: ['common'],
    interpolation: { escapeValue: false },
    resources: {
      en: {
        common: {
          scenarioLab: {
            interpretation: {
              title: 'Interpretation',
              description: 'Translate model outputs into decision language.',
              and: 'and',
              sections: {
                whatChanged: 'What changed',
                whyItChanged: 'Why it changed',
                keyRisks: 'Key risks',
                policyImplications: 'Policy implications',
                suggestedNextScenarios: 'Suggested next scenarios',
              },
              drivers: {
                externalDemand: 'external demand',
                exchangeRate: 'exchange-rate path',
              },
              items: {
                gdpGrowthDelta: 'GDP growth is {{delta}} pp versus baseline by 2026 Q4.',
                mainDrivers: 'Main drivers are {{drivers}}.',
                passThroughRisk:
                  'Pass-through may be stronger than assumed when exchange-rate shocks are persistent.',
                targetedMitigation:
                  'Use targeted mitigation if downside scenarios widen the growth-inflation trade-off.',
              },
              suggestedNext: {
                'external-slowdown': 'Deepen external-demand slowdown',
              },
              aiAttribution: {
                assisted: {
                  title: 'AI-assisted · Unreviewed draft',
                  body:
                    'AI-assisted draft. Generated by model output, not yet reviewed by CERR analytical staff. Do not cite, export, or share externally.',
                },
                reviewed: {
                  title: 'AI-assisted · Reviewed {{reviewed_at}}',
                  body:
                    'AI-assisted narrative, reviewed by {{reviewer_name}} on {{review_date}}. Cleared for internal use and citation.',
                },
              },
            },
          },
        },
      },
      ru: {
        common: {
          scenarioLab: {
            interpretation: {
              title: 'Интерпретация',
              description: 'Преобразуйте результаты моделей в язык решений.',
              and: 'и',
              sections: {
                whatChanged: 'Что изменилось',
                whyItChanged: 'Почему это изменилось',
                keyRisks: 'Ключевые риски',
                policyImplications: 'Политические последствия',
                suggestedNextScenarios: 'Следующие сценарии',
              },
              drivers: {
                externalDemand: 'внешний спрос',
                exchangeRate: 'траектория обменного курса',
              },
              items: {
                gdpGrowthDelta: 'Рост ВВП на {{delta}} п.п. к базовой траектории к 2026 Q4.',
                mainDrivers: 'Основные драйверы: {{drivers}}.',
                passThroughRisk:
                  'Перенос курса в цены может быть сильнее, если курсовой шок сохраняется.',
                targetedMitigation:
                  'Используйте адресные меры, если негативные сценарии ухудшают компромисс между ростом и инфляцией.',
              },
              suggestedNext: {
                'external-slowdown': 'Углубить сценарий внешнего замедления',
              },
              aiAttribution: {
                assisted: {
                  title: 'С участием ИИ · непроверенный черновик',
                  body:
                    'Черновик с участием ИИ. Сгенерирован на основе результатов модели, ещё не проверен аналитическим персоналом CERR. Не цитировать, не экспортировать и не передавать вне организации.',
                },
                reviewed: {
                  title: 'С участием ИИ · проверено {{reviewed_at}}',
                  body:
                    'Нарратив с участием ИИ, проверен {{reviewer_name}} {{review_date}}. Допущен для внутреннего использования и цитирования.',
                },
              },
            },
          },
        },
      },
    },
  })
  return instance
}

function buildInterpretation(
  overrides: Partial<ScenarioLabInterpretation> = {},
): ScenarioLabInterpretation {
  return {
    what_changed: ['GDP growth softened.'],
    why_it_changed: ['External demand weakened.'],
    key_risks: ['Persistent imported inflation.'],
    policy_implications: ['Tighten policy sequencing.'],
    suggested_next_scenarios: ['External slowdown with fiscal consolidation.'],
    metadata: { generation_mode: 'template' },
    ...overrides,
  }
}

describe('InterpretationPanel', () => {
  it('does not render AI attribution treatment in template mode', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({ metadata: { generation_mode: 'template' } })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.doesNotMatch(markup, /class="ai-attribution/)
    assert.doesNotMatch(markup, /AI-assisted/)
  })

  it('ignores legacy top-level governance fields without typed metadata', async () => {
    const i18n = await createTestI18n()
    const legacyInterpretation = {
      ...buildInterpretation({ metadata: undefined }),
      generation_mode: 'reviewed',
      reviewer_name: 'Legacy Reviewer',
      reviewed_at: '2026-04-20T09:15:00+05:00',
    } as ScenarioLabInterpretation
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel interpretation={legacyInterpretation} />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.doesNotMatch(markup, /class="ai-attribution/)
    assert.doesNotMatch(markup, /Legacy Reviewer/)
  })

  it('renders the adopted unreviewed warning in assisted mode', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({ metadata: { generation_mode: 'assisted' } })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /class="ai-attribution ai-attribution--assisted"/)
    assert.match(markup, /AI-assisted · Unreviewed draft/)
    assert.match(markup, /Do not cite, export, or share externally/)
  })

  it('renders reviewer meta line when reviewed mode carries a reviewer name', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              metadata: {
                generation_mode: 'reviewed',
                reviewer_name: 'M. Usmanov',
                reviewed_at: '2026-04-20T09:15:00+05:00',
              },
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /class="ai-attribution ai-attribution--reviewed"/)
    assert.match(markup, /AI-assisted · Reviewed/)
    assert.match(markup, /reviewed by M\. Usmanov/)
    assert.match(markup, /Cleared for internal use and citation/)
  })

  it('falls back to assisted treatment when reviewed metadata is incomplete', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              metadata: {
                generation_mode: 'reviewed',
                reviewer_name: 'M. Usmanov',
              },
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /AI-assisted · Unreviewed draft/)
    assert.match(markup, /Do not cite, export, or share externally/)
    assert.doesNotMatch(markup, /Cleared for internal use and citation/)
  })

  it('renders clickable Link anchors for suggested_next entries', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              suggested_next: [
                {
                  label: 'Pair with a remittance shock',
                  target_route: '/scenario-lab',
                  target_preset: 'russia_slowdown',
                },
                {
                  label: 'Compare with baseline and tight-money',
                  target_route: '/comparison',
                },
              ],
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /href="\/scenario-lab\?preset=russia_slowdown"/)
    assert.match(markup, /href="\/comparison"/)
  })

  it('localizes generated QPM interpretation sentences and suggested links', async () => {
    const i18n = await createTestI18n('ru')
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              what_changed: ['GDP growth is -0.2 pp versus baseline by 2026 Q4.'],
              why_it_changed: ['Main drivers are external demand and exchange-rate path.'],
              key_risks: [
                'Pass-through may be stronger than assumed when exchange-rate shocks are persistent.',
              ],
              policy_implications: [
                'Use targeted mitigation if downside scenarios widen the growth-inflation trade-off.',
              ],
              suggested_next: [
                {
                  label: 'Deepen external-demand slowdown',
                  target_route: '/scenario-lab',
                  target_preset: 'external-slowdown',
                },
              ],
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /Рост ВВП на -0\.2 п\.п\./)
    assert.match(markup, /Основные драйверы: внешний спрос и траектория обменного курса/)
    assert.match(markup, /Углубить сценарий внешнего замедления/)
    assert.doesNotMatch(markup, /GDP growth is/)
    assert.doesNotMatch(markup, /Main drivers are/)
    assert.doesNotMatch(markup, /Deepen external-demand slowdown/)
  })
})
